version: 1.0.0

client:
  organization: Org1
  logging:
    level: info
  # Root of the MSP directories with keys and certs.
  cryptoconfig:
    path: D:\workspace\go\src\github.com\lifegoeson\blockchain-explorer\crypto-config
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp

channels:
  channel2:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true

        chaincodeQuery: true

        ledgerQuery: true

        eventSource: true
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true

        chaincodeQuery: true

        ledgerQuery: true

        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations\org1.example.com\users\{username}@org1.example.com\msp
    peers:
      - peer0.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://114.115.204.233:7051

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: D:\workspace\go\src\github.com\lifegoeson\blockchain-explorer\crypto-config\peerOrganizations\org1.example.com\tlsca\tlsca.org1.example.com-cert.pem

entityMatchers:
  peer:
    - pattern: (\w+).org1.example.(\w+)
      urlSubstitutionExp: grpcs://114.115.204.233:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com
